// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScheduledTask(arg1) {
  return window['go']['main']['App']['AddScheduledTask'](arg1);
}

export function CheckWhatsAppConnection() {
  return window['go']['main']['App']['CheckWhatsAppConnection']();
}

export function ConnectExistingDevice() {
  return window['go']['main']['App']['ConnectExistingDevice']();
}

export function DisconnectWhatsApp() {
  return window['go']['main']['App']['DisconnectWhatsApp']();
}

export function GetAllScheduledTasks() {
  return window['go']['main']['App']['GetAllScheduledTasks']();
}

export function GetAutoReplyConfig() {
  return window['go']['main']['App']['GetAutoReplyConfig']();
}

export function GetChats() {
  return window['go']['main']['App']['GetChats']();
}

export function GetConnectionEvents() {
  return window['go']['main']['App']['GetConnectionEvents']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetContactInfo(arg1) {
  return window['go']['main']['App']['GetContactInfo'](arg1);
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetScheduledTask(arg1) {
  return window['go']['main']['App']['GetScheduledTask'](arg1);
}

export function GetSchedulerStats() {
  return window['go']['main']['App']['GetSchedulerStats']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveScheduledTask(arg1) {
  return window['go']['main']['App']['RemoveScheduledTask'](arg1);
}

export function RequestPairingCode(arg1) {
  return window['go']['main']['App']['RequestPairingCode'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function StartNewConnection() {
  return window['go']['main']['App']['StartNewConnection']();
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}

export function UpdateAutoReplyConfig(arg1) {
  return window['go']['main']['App']['UpdateAutoReplyConfig'](arg1);
}

export function UpdateScheduledTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateScheduledTask'](arg1, arg2);
}
