// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {whatsapp} from '../models';

export function AddScheduledTask(arg1:whatsapp.ScheduledTask):Promise<void>;

export function CheckWhatsAppConnection():Promise<whatsapp.ConnectionStatus>;

export function ConnectExistingDevice():Promise<void>;

export function DisconnectWhatsApp():Promise<void>;

export function GetAllScheduledTasks():Promise<Array<whatsapp.ScheduledTask>>;

export function GetAutoReplyConfig():Promise<whatsapp.AutoReplyConfig>;

export function GetChats():Promise<Array<whatsapp.Chat>>;

export function GetConnectionEvents():Promise<any>;

export function GetConnectionStatus():Promise<whatsapp.ConnectionStatus>;

export function GetContactInfo(arg1:string):Promise<whatsapp.ContactInfo>;

export function GetContacts():Promise<Array<whatsapp.Contact>>;

export function GetMessages(arg1:string):Promise<Array<whatsapp.Message>>;

export function GetScheduledTask(arg1:string):Promise<whatsapp.ScheduledTask>;

export function GetSchedulerStats():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveScheduledTask(arg1:string):Promise<void>;

export function RequestPairingCode(arg1:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function StartNewConnection():Promise<void>;

export function TestAIConnection(arg1:string):Promise<string>;

export function UpdateAutoReplyConfig(arg1:whatsapp.AutoReplyConfig):Promise<void>;

export function UpdateScheduledTask(arg1:string,arg2:whatsapp.ScheduledTask):Promise<void>;
